name: Build and Publish Dev Docker Image

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Get repository name in lowercase
        id: repo_name
        run: echo "REPO_NAME=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_OUTPUT
          
      - name: Get version from package.json
        id: package_version
        run: echo "VERSION=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT
        
      - name: Get short SHA
        id: short_sha
        run: echo "SHA=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
        
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}:dev
            ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}:${{ steps.package_version.outputs.VERSION }}-dev
            ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}:${{ steps.package_version.outputs.VERSION }}-${{ steps.short_sha.outputs.SHA }}
          cache-from: type=registry,ref=ghcr.io/${{ steps.repo_name.outputs.REPO_NAME }}:dev
          cache-to: type=inline